# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/arch/exp6/Exp6/Exp6.srcs/sources_1/ip/multiplier/multiplier.xci
# IP: The module: 'multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/arch/exp6/Exp6/Exp6.srcs/sources_1/ip/multiplier/multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/arch/exp6/Exp6/Exp6.srcs/sources_1/ip/multiplier/multiplier.xci
# IP: The module: 'multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/arch/exp6/Exp6/Exp6.srcs/sources_1/ip/multiplier/multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
