# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/arch/exp4/Exp4/Exp4.cache/wt [current_project]
set_property parent.project_path F:/arch/exp4/Exp4/Exp4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/arch/exp4/Exp4/Exp4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/arch/exp4/Exp4/Exp4.sim/sim_1/behav/xsim/mem_test.coe
read_verilog {
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/function.vh
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/cache/addr_define.vh
}
read_verilog -library xil_defaultlib {
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/ALU.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/CPUTEST.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/Code2Inst.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/CtrlUnit.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/Font816.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/HazardDetectionUnit.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/ImmGen.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/common/MUX2T1_32.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/common/MUX4T1_32.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/common/REG32.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/REG_EX_MEM.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/REG_ID_EX.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/REG_IF_ID.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/REG_MEM_WB.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/RV32core.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/core/Regs.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/VGATEST.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/common/add_32.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/btn_scan.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/cache/cache.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/clk_diff.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/auxillary/clkdiv.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/common/cmp_32.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/cache/cmu.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/cache/sim/data_ram.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/auxillary/debug_analyzer.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/debug_clk.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/display.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/my_clk_gen.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/parallel2serial.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/auxillary/vga.v
  F:/arch/exp4/Exp4/Exp4.srcs/sources_1/imports/code/top.v
}
read_ip -quiet F:/arch/exp4/Exp4/Exp4.srcs/sources_1/ip/ROM_D/ROM_D.xci
set_property used_in_implementation false [get_files -all f:/arch/exp4/Exp4/Exp4.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/arch/exp4/Exp4/Exp4.srcs/constrs_1/imports/code/constraint.xdc
set_property used_in_implementation false [get_files F:/arch/exp4/Exp4/Exp4.srcs/constrs_1/imports/code/constraint.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7k325tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
